name: Build Docker Image with Podman

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'
    tags:
      - 'v*'  # Run on tag pushes that start with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version
      
      - name: Build image with Podman
        run: |
          podman build -t ci-image:latest .
      
      - name: Test image
        run: |
          podman run --rm ci-image:latest echo "Container test successful"
  
  release:
    name: Release Image
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      # Registry login and push steps - only run on tag commits
      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag and push image
        run: |
          # Extract tag name from ref
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Tag with both the specific version and latest
          podman tag ci-image:latest ghcr.io/${{ github.repository }}/ci-image:${TAG_NAME}
          podman tag ci-image:latest ghcr.io/${{ github.repository }}/ci-image:latest
          # Push both tags
          podman push ghcr.io/${{ github.repository }}/ci-image:${TAG_NAME}
          podman push ghcr.io/${{ github.repository }}/ci-image:latest